version: '3' 

services:

  proxy:
    image: jwilder/nginx-proxy:alpine
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    container_name: nextcloud-proxy
    networks:
      nextcloud_network:
            ipv4_address: 172.24.0.3
    ports:
      - 445:80
      - 446:443
    volumes:
      - ./proxy/conf.d/my_custom_proxy_settings.conf:/etc/nginx/conf.d/my_custom_proxy_settings.conf
      - ./proxy/conf.d:/etc/nginx/conf.d:rw
      - ./proxy/vhost.d:/etc/nginx/vhost.d:rw
      - ./proxy/html:/usr/share/nginx/html:rw
      - ./proxy/certs:/etc/nginx/certs:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: unless-stopped
   
  db:
    image: postgres:13
    container_name: nextcloud-postgres
    networks:
      nextcloud_network:
            ipv4_address: 172.24.0.7
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_PASSWORD=${NEXTCLOUD_PG_PASSWORD}
    restart: unless-stopped
  
  app:
    image: nextcloud:latest
    container_name: nextcloud-app
    networks:
      nextcloud_network:
            ipv4_address: 172.24.0.5
    depends_on:
      - proxy
      - db
    volumes:
      - ./nextcloud:/var/www/html
      - ./app/config:/var/www/html/config
      - ./app/custom_apps:/var/www/html/custom_apps
      - ./app/data:/var/www/html/data
      - ./app/themes:/var/www/html/themes
      - /etc/localtime:/etc/localtime
      - /mnt/backup/documents/:/documents
      - /mnt/backup/backup/vvy_smartphones/record_call_vvy/:/record_call_vvy
      - /mnt/backup/backup/vvy_backup_work/:/vvy_backup_work
      - /mnt/backup/backup/vvy_smartphones/camera/:/camera_vvy
      - /mnt/backup/backup/angel_smartphones/camera_device_angel/:/camera_device_angel
      - /mnt/backup/photo/:/photo
      - /mnt/backup/my videos/:/my videos
      - /mnt/media/share/:/share
    environment:
      - VIRTUAL_HOST=${EXTERNAL_IP}
    restart: unless-stopped  

  onlyoffice:
    container_name: onlyoffice-documentserver
    networks:
      nextcloud_network:
            ipv4_address: 172.24.0.6
    image: onlyoffice/documentserver:latest
    depends_on:
      - proxy
      - db
      - app
    restart: always
    volumes:
      - ./DocumentServer/data:/var/www/onlyoffice/Data
      - ./proxy/certs/dhparam.pem:/var/www/onlyoffice/Data/certs/dhparam.pem
      - ./proxy/certs/test.cakecloud.info/key.pem:/var/www/onlyoffice/Data/certs/onlyoffice.key
      - ./proxy/certs/test.cakecloud.info/cert.pem:/var/www/onlyoffice/Data/certs/onlyoffice.crt
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=${ONLYOFFICE_SECRET}
    ports:
      - '8889:80'
      - '4443:443'    
networks:
    nextcloud_network:
      driver: bridge
      ipam:
        config:
            - subnet: '172.24.0.0/24'
